<?php
/**
 * Created by PhpStorm.
 * User: C0RRUP70R
 * Date: 20.01.2018
 * Time: 16:47
 */

namespace app\models;


use yii\base\Model;

class Detail extends Model
{
    private $detail_pk;
    private $nazev;
    private $rozmer;
    private $material;
    private $medium;
    private $kategorie;
    private $img;

    /**
     * @return mixed
     */
    public function getDetailPk()
    {
        return $this->detail_pk;
    }

    /**
     * @param mixed $detail_pk
     */
    public function setDetailPk($detail_pk)
    {
        $this->detail_pk = $detail_pk;
    }

    /**
     * @return mixed
     */
    public function getNazev()
    {
        return $this->nazev;
    }

    /**
     * @param mixed $nazev
     */
    public function setNazev($nazev)
    {
        $this->nazev = $nazev;
    }

    /**
     * @return mixed
     */
    public function getRozmer()
    {
        return $this->rozmer;
    }

    /**
     * @param mixed $rozmer
     */
    public function setRozmer($rozmer)
    {
        $this->rozmer = $rozmer;
    }

    /**
     * @return mixed
     */
    public function getMaterial()
    {
        return $this->material;
    }

    /**
     * @param mixed $material
     */
    public function setMaterial($material)
    {
        $this->material = $material;
    }

    /**
     * @return mixed
     */
    public function getMedium()
    {
        return $this->medium;
    }

    /**
     * @param mixed $medium
     */
    public function setMedium($medium)
    {
        $this->medium = $medium;
    }

    /**
     * @return mixed
     */
    public function getKategorie()
    {
        return $this->kategorie;
    }

    /**
     * @param mixed $kategorie
     */
    public function setKategorie($kategorie)
    {
        $this->kategorie = $kategorie;
    }

    /**
     * @return mixed
     */
    public function getImg()
    {
        return $this->img;
    }

    /**
     * @param mixed $img
     */
    public function setImg($img)
    {
        $this->img = $img;
    }


    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public static function getAll()
    {
        $sql = "SELECT
  nazev,
  img,
  r.popis  AS rozmer,
  m.popis  AS material,
  me.popis AS medium,
  c.popis  AS kategorie
FROM detail
  JOIN rozmer AS r USING (rozmer_pk)
  JOIN material AS m USING (material_pk)
  JOIN medium AS me USING (medium_pk)
  JOIN category AS c USING (category_pk);";

        $command = \Yii::$app->db->createCommand($sql);
        $arr = $command->queryAll();

        return $arr;
    }

    /**
     * @return array
     */
    public static function getAllBasic()
    {
        $sql = "
SELECT
  nazev,
  img,
  detail_pk
FROM detail";

        $command = \Yii::$app->db->createCommand($sql);
        $arr = $command->queryAll();

        return $arr;
    }

    public static function getByPk($pk)
    {
        $sql = "SELECT
  nazev,
  img,
  r.popis  AS rozmer,
  m.popis  AS material,
  me.popis AS medium,
  c.popis  AS kategorie
FROM detail
  JOIN rozmer AS r USING (rozmer_pk)
  JOIN material AS m USING (material_pk)
  JOIN medium AS me USING (medium_pk)
  JOIN category AS c USING (category_pk)
WHERE detail_pk = :pk;";
        $params = array(':pk' => $pk);

        $command = \Yii::$app->db->createCommand($sql)->bindValues($params);
        $arr = $command->queryOne();
        $m = new Detail($arr);
        return $m;
    }
}